### ISSUE TITLE
[1pt ] Setup Backend

### ISSUE THREAD

**Issue by RichardChileya** [RichardChileya/booking-app-back-end#1]
### Changes : 
- Setup kanban for the backend of the booking app project
- Assign roles to team members 
- Setup Kanban for frontend 
- Assign roles to team members 
- We are four members in the group i.e; 
  - Student A is @samlorlah 
  - Student B is @RichardChileya 
  - Student C is @tashisrael 
  - Student D is @Recillah-Khamala 
- Screenshot
  - ![image](https://user-images.githubusercontent.com/91204164/222435343-90a698c1-7178-4e32-a0ed-8b32768bb4ac.png)

- [Link to the Kanban Project](https://github.com/RichardChileya/booking-app-back-end/projects/1)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However there are some issues preventing me from giving the 👍 


## Highlights
- All issues have description ✔️ 
- Weight for tasks seem appropriate ✔️ 

## Required Changes
- Tasks assigned to team members should be  equitable and therefore there should not be more than a 5 pt difference in task assignments. In this case @tashisrael has way more tasks assigned than everyone else. Currently don't meet this requirement✖️ 
- Ideally this requirement would have made submission invalid, but I forgot to spot this originally so did not think it were fair to mark it as invalid again, so please address this: Info concerning the number of persons on your team should be in this issue description (Whether it means you mention the github users. their names or just the number memebers in the team (or all)).  You currently do not meet this requirement ✖️ 
- 
## Optional suggestions
- [OPTIONAL] Consider adding laels to your issues, it'd make it easier to among different tasks and even make it easier to filter different types of tasks. Do you think this is something you can do ❓ 
- 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this issue. However, I strongly recommend you to take them into account as they can make your Kanban better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- You corrected inequitable distribution of tasks and all good now ✔️ 
- Representation of number of members in team is in the issue description ✔️ 

## Optional suggestions
- [OPTIONAL] Consider adding laels to your issues, it'd make it easier to among different tasks and even make it easier to filter different types of tasks. ❓  

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
